<?php
// Autogenerated by "make sri" (and srihash_files.txt).
$GLOBALS["SRIHASHES"] = array(
"css/font-awesome.min.css" => "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN",
"css/style.css" => "sha384-UxS+bLxZct1tw0ZXF+U0xWLutfeup3rwndfZSs62jje3SnnSZopVDqwVQ55nhI4V",
"js/jquery-min.js" => "sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f",
"js/phonebook.js" => "sha384-zBnSL70GoBGd7GUjwtkCMdi6T39nm680i7/2sxmn9IzSJhmaDsMnbxywAjoU9dei",
);
?>
