<?php
// Autogenerated by "make sri" (and srihash_files.txt).
$GLOBALS["SRIHASHES"] = array(
"css/font-awesome.min.css" => "sha384-X7L1bhgb36bF1iFvaqvhgpaGpayKM+vXNNYRlF89BFA5s3vi1qZ8EX9086RlZjy1",
"css/style.css" => "sha384-upsq5NXIBEqpEXX8zZGMyhsvciKca8u4Aqhpx2QxAuft+g4PeMz7WXfU6DpS9JHE",
"js/common.js" => "sha384-pMmCBo/jjOf+CXleBlKkjcKdt8/u3b54klwB/uaSmBwVQ4ltgQkveCxSJGxRJ5Q0",
"js/edit.js" => "sha384-b0InpttB8kkNr/8L1Dn55WzdD70UnxjtW4jbLPKmxJKIBL1oysEL2Dgwva/oTflj",
"js/prototype.js" => "sha384-UMMEM11r0EqZNKWl1NnkWxCEtyWhw2UYJgUAgJGkFW+g007xJcJOTycBT5LIoyKQ",
"js/view-cards.js" => "sha384-iJ4Vu3pMxX7/mwS1KSwTgBnzuuYXt2FEO8aNBh/4LNYzP6leGYx1/CmqigtAKlxL",
"js/view-faces.js" => "sha384-xuPN6M+jzgEbIJ86Rim0pxmpEBZbPh5B7hNTZx/G9sExYyZyv/VPHgitxVjsc7lI",
"js/view-tree.js" => "sha384-kgrnc5n5no8IKYoaEFQFEZ+g1SdgEpdZS5mhAxop3IEWD7eAktWyfhVb7u9svRAw",
);
?>
