SHELL := /bin/bash

.PHONY: sri
sri:
	{ \
	    echo '<?php' ; \
	    echo '// Autogenerated by "make sri" (and srihash_files.txt).' ; \
	    echo '$$GLOBALS["SRIHASHES"] = array(' ; \
	    for file in `grep -v '^#' srihash_files.txt | sort` ; do \
	        printf '"%s" => "sha384-%s",\n' $$file `openssl dgst -sha384 -binary < $$file | openssl enc -base64 -A` ; \
	    done ; \
	    echo ');' ; \
	    echo '?>' ; \
	} > config-srihashes.php
	@echo
	@ls -al srihash_files.txt config-srihashes.php
	@echo
	git diff -- srihash_files.txt config-srihashes.php
